
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// O `datasource` aqui é o que o CLI da Prisma (prisma generate, migrate
// deploy, etc.) realmente usa para conectar — não o bloco `datasource db`
// do schema.prisma, que só vale para o Prisma Client em runtime (o app
// em produção, que instancia PrismaClient diretamente e nunca passa por
// este arquivo). Por isso apontamos para a conexão DIRETA (sem pooler):
// o `migrate deploy` precisa manter um `pg_advisory_lock` (lock
// consultivo) durante a migração, e o pooler do Neon (PgBouncer em modo
// transaction) não sustenta esse lock de sessão — cada statement pode
// cair numa conexão física diferente, e o CLI trava até estourar em
// P1002. Isso não afeta o app: ele continua lendo `env("DATABASE_URL")`
// (com pooler) do schema.prisma normalmente. Sem pooler envolvido (dev
// local), DATABASE_URL_UNPOOLED e DATABASE_URL apontam para o mesmo
// Postgres, então tanto faz.
//
// Lê process.env diretamente (não o helper `env()` do prisma/config, que
// valida e lança na hora de carregar este arquivo) — senão até `prisma
// generate` (que não precisa de banco nenhum) quebraria sem essas
// variáveis, como no primeiro `npm install` de um deploy na Vercel antes
// do banco ser conectado ao projeto.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL_UNPOOLED ?? process.env.DATABASE_URL ?? "",
  },
});
