
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `datasource.url` lê process.env diretamente (não o helper `env()` do
// prisma/config, que valida e lança na hora de carregar este arquivo).
// schema.prisma já declara `datasource db { url = env("DATABASE_URL") }`,
// que só é lido quando um comando realmente precisa conectar — o valor
// aqui não é usado por `prisma generate`. Se a validação eager do `env()`
// ficasse, até `prisma generate` (que não precisa de banco nenhum)
// quebraria sem DATABASE_URL, como no primeiro `npm install` de um deploy
// na Vercel antes do banco ser conectado ao projeto.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
